# Site settings
title: Acid Blog
header-img: img/home-bg.jpg
email: acidjunk@gmail.com
copyright_name: Acidjunky 
description: "To create problemz for solutionz :: a blog about development, science live and music."
baseurl: ""
url: "https://acidjunk.github.io"
twitter_username: acidjunk
github_username:  acidjunk
facebook_username:  IronSummitMedia
email_username:  acidjunk@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
